workflows:
  react-native-android:
    name: React Native Android
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      android_signing:
        - khxtnd
      groups:
        - khTeam
      vars:
        PACKAGE_NAME: "com.healing_app"
    scripts:
      - npm install
      - echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"
      - name: Build Android release
        script: | 
          cd android
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - thanhtamthipham2k1@gmail.com
        notify:
          success: true
          failure: false